name: moodle_dk
services:
  mariadb:
    container_name: dbm_moodle
    image: docker.io/bitnami/mariadb:11.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./mariadb_data:/bitnami/mariadb
  moodle:
    container_name: moodle
    image: docker.io/bitnami/moodle:4.4
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # SMTP service configuration
      #- MOODLE_SMTP_HOST=smtp.gmail.com
      #- MOODLE_SMTP_PORT=587
      #- MOODLE_SMTP_USER=your_email@gmail.com
      #- MOODLE_SMTP_PASSWORD=your_password
      #- MOODLE_SMTP_PROTOCOL=tls
      # Proxy reverse service configuration
      #- MOODLE_HOST=example.com
      #- MOODLE_REVERSEPROXY=true
      #- MOODLE_SSLPROXY=true
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
