name: moodle_db
services:
  mariadb:
    container_name: mariadb_m
    image: docker.io/bitnami/mariadb:11.4
    restart: always
    ports:
      - 3307:3306
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      # Configurar como propietario a 1001:1001
      - ./mariadb_data:/bitnami/mariadb:rw
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
