name: moodle_dk
services:
  mariadb:
    container_name: mariadb_m
    image: docker.io/bitnami/mariadb:11.4
    restart: always
    ports:
      - 3307:3306
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      # Configurar como propietario a 1001:1001
      - ./mariadb_data:/bitnami/mariadb:rw
    #healthcheck:
    #  test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
    #  interval: 15s
    #  timeout: 5s
    #  retries: 6
  moodle:
    container_name: moodle
    #image: docker.io/bitnami/moodle:latest
    build:
      context: ./4.4-debian-12
      dockerfile: Dockerfile
      args:
        - EXTRA_LOCALES=fr_FR.UTF-8 UTF-8, de_DE.UTF-8 UTF-8, it_IT.UTF-8 UTF-8, es_ES.UTF-8 UTF-8
    ports:
      - "8080:8080"
      - "8443:443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb_m
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # SMTP service configuration
      #- MOODLE_SMTP_HOST=smtp.gmail.com
      #- MOODLE_SMTP_PORT=587
      #- MOODLE_SMTP_USER=your_email@gmail.com
      #- MOODLE_SMTP_PASSWORD=your_password
      #- MOODLE_SMTP_PROTOCOL=tls
      # Proxy reverse service configuration
      #- MOODLE_HOST=example.com
      #- MOODLE_REVERSEPROXY=true
      #- MOODLE_SSLPROXY=true
    volumes:
      - ./moodle_data:/bitnami/moodle:rw
      - ./moodledata_data:/bitnami/moodledata:rw
